"""empty message

Revision ID: fb1fceb40b93
Revises: c0d287985876
Create Date: 2023-01-16 22:27:44.356263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1fceb40b93'
down_revision = 'c0d287985876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=1526), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
